security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        in_memory: { memory: ~ }

        user_db_provider:
            entity:
                  class: App:User
                  property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: user_db_provider
            form_login:
                login_path: /
                check_path: /sign-in
                default_target_path: /home
                username_parameter: "sign_in_form[username]"
                password_parameter: "sign_in_form[password]"
            logout:
                path:   /log-out
                target: /
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            entry_point: App\Security\UserAuthenticator
            remember_me:
                secret:   '0ABD46469DED93862393FE7000B43A33FEBA6A8761B1B23B0EC90FFB7181F498'
                lifetime: 604800 # 1 week in seconds


    access_control:
