<?php
declare(strict_types=1);

namespace App\Tests\Service;

use App\Service\DevMessengerService;
use PHPUnit\Framework\TestCase;

/**
 * Class DevMessengerServiceTest
 * @package App\Tests\Service
 */
class DevMessengerServiceTest extends TestCase
{

    private $devMessengerService;
    private $commandService;
    private $addMessageCommand;
    private $createConversationCommand;
    private $userRepository;

    public function setUp(): void
    {
        $this->devMessengerService = new DevMessengerService();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testOnClose()
    {

    }

    public function testOnError()
    {

    }

    public function testOnMessage()
    {

    }

    public function testOnOpen()
    {

    }
}
